version: "3.4"

# Development environment override
services:
  app:
    volumes:
      - ./docker/php/conf.d/symfony.dev.ini:/usr/local/etc/php/conf.d/symfony.ini
      - ./var/app.db:/srv/app/var/app.db

    environment:
      APP_ENV: dev
      DATABASE_URL: sqlite:////srv/app/var/app.db